In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
%matplotlib inline
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import preprocessing

In [2]:
# C:\Users\Hansen Marcelino\Documents\DNAlytics\tipe-tiperumah\jarak\DataBersih.csv
pd.set_option('display.max_column', None)

In [3]:
df = pd.read_csv(r'C:\Users\Hansen Marcelino\Documents\DNAlytics\tipe-tiperumah\jarak\DataBersih.csv')
df

Unnamed: 0         Suburb           Address  Rooms Type      Price  \
0               0     Abbotsford      85 Turner St      2    h  1480000.0   
1               1     Abbotsford   25 Bloomburg St      2    h  1035000.0   
2               2     Abbotsford      5 Charles St      3    h  1465000.0   
3               3     Abbotsford  40 Federation La      3    h   850000.0   
4               4     Abbotsford       55a Park St      4    h  1600000.0   
...           ...            ...               ...    ...  ...        ...   
12908       13574    Westmeadows        9 Black St      3    h   582000.0   
12909       13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0   
12910       13576   Williamstown     77 Merrett Dr      3    h  1031000.0   
12911       13577   Williamstown       83 Power St      3    h  1170000.0   
12912       13579     Yarraville        6 Agnes St      4    h  1285000.0   

      Method   SellerG        Date  Distance  Postcode  Bedroom2  Bathroom  \
0          S    Biggin  2016-03-12       2.5    3067.0       2.0       1.0   
1          S    Biggin  2016-04-02       2.5    3067.0       2.0       1.0   
2         SP    Biggin  2017-04-03       2.5    3067.0       3.0       2.0   
3         PI    Biggin  2017-04-03       2.5    3067.0       3.0       2.0   
4         VB    Nelson  2016-04-06       2.5    3067.0       3.0       1.0   
...      ...       ...         ...       ...       ...       ...       ...   
12908      S       Red  2017-08-26      16.5    3049.0       3.0       2.0   
12909      S     Barry  2017-08-26      16.7    3150.0       4.0       2.0   
12910     SP  Williams  2017-08-26       6.8    3016.0       3.0       2.0   
12911      S     Raine  2017-08-26       6.8    3016.0       3.0       2.0   
12912     SP   Village  2017-08-26       6.3    3013.0       4.0       1.0   

       Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  \
0      1.0     202.0         151.0     1964.0       Yarra  -37.79960   
1      0.0     156.0          79.0     1900.0       Yarra  -37.80790   
2      0.0     134.0         150.0     1900.0       Yarra  -37.80930   
3      1.0      94.0         151.0     1964.0       Yarra  -37.79690   
4      2.0     120.0         142.0     2014.0       Yarra  -37.80720   
...    ...       ...           ...        ...         ...        ...   
12908  2.0     256.0         151.0     1964.0         NaN  -37.67917   
12909  2.0     652.0         151.0     1981.0         NaN  -37.90562   
12910  2.0     333.0         133.0     1995.0         NaN  -37.85927   
12911  4.0     436.0         151.0     1997.0         NaN  -37.85274   
12912  1.0     362.0         112.0     1920.0         NaN  -37.81188   

       Longtitude                  Regionname  Propertycount    Age  
0       144.99840       Northern Metropolitan         4019.0   52.0  
1       144.99340       Northern Metropolitan         4019.0  116.0  
2       144.99440       Northern Metropolitan         4019.0  117.0  
3       144.99690       Northern Metropolitan         4019.0   53.0  
4       144.99410       Northern Metropolitan         4019.0    2.0  
...           ...                         ...            ...    ...  
12908   144.89390       Northern Metropolitan         2474.0   53.0  
12909   145.16761  South-Eastern Metropolitan         7392.0   36.0  
12910   144.87904        Western Metropolitan         6380.0   22.0  
12911   144.88738        Western Metropolitan         6380.0   20.0  
12912   144.88449        Western Metropolitan         6543.0   97.0  

[12913 rows x 23 columns]

In [4]:
df['Type'] = df['Type'].map({
    'h' : 0,
    'u' : 1,
    't' :2
})

In [5]:
df

Unnamed: 0         Suburb           Address  Rooms  Type      Price  \
0               0     Abbotsford      85 Turner St      2     0  1480000.0   
1               1     Abbotsford   25 Bloomburg St      2     0  1035000.0   
2               2     Abbotsford      5 Charles St      3     0  1465000.0   
3               3     Abbotsford  40 Federation La      3     0   850000.0   
4               4     Abbotsford       55a Park St      4     0  1600000.0   
...           ...            ...               ...    ...   ...        ...   
12908       13574    Westmeadows        9 Black St      3     0   582000.0   
12909       13575  Wheelers Hill      12 Strada Cr      4     0  1245000.0   
12910       13576   Williamstown     77 Merrett Dr      3     0  1031000.0   
12911       13577   Williamstown       83 Power St      3     0  1170000.0   
12912       13579     Yarraville        6 Agnes St      4     0  1285000.0   

      Method   SellerG        Date  Distance  Postcode  Bedroom2  Bathroom  \
0          S    Biggin  2016-03-12       2.5    3067.0       2.0       1.0   
1          S    Biggin  2016-04-02       2.5    3067.0       2.0       1.0   
2         SP    Biggin  2017-04-03       2.5    3067.0       3.0       2.0   
3         PI    Biggin  2017-04-03       2.5    3067.0       3.0       2.0   
4         VB    Nelson  2016-04-06       2.5    3067.0       3.0       1.0   
...      ...       ...         ...       ...       ...       ...       ...   
12908      S       Red  2017-08-26      16.5    3049.0       3.0       2.0   
12909      S     Barry  2017-08-26      16.7    3150.0       4.0       2.0   
12910     SP  Williams  2017-08-26       6.8    3016.0       3.0       2.0   
12911      S     Raine  2017-08-26       6.8    3016.0       3.0       2.0   
12912     SP   Village  2017-08-26       6.3    3013.0       4.0       1.0   

       Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  \
0      1.0     202.0         151.0     1964.0       Yarra  -37.79960   
1      0.0     156.0          79.0     1900.0       Yarra  -37.80790   
2      0.0     134.0         150.0     1900.0       Yarra  -37.80930   
3      1.0      94.0         151.0     1964.0       Yarra  -37.79690   
4      2.0     120.0         142.0     2014.0       Yarra  -37.80720   
...    ...       ...           ...        ...         ...        ...   
12908  2.0     256.0         151.0     1964.0         NaN  -37.67917   
12909  2.0     652.0         151.0     1981.0         NaN  -37.90562   
12910  2.0     333.0         133.0     1995.0         NaN  -37.85927   
12911  4.0     436.0         151.0     1997.0         NaN  -37.85274   
12912  1.0     362.0         112.0     1920.0         NaN  -37.81188   

       Longtitude                  Regionname  Propertycount    Age  
0       144.99840       Northern Metropolitan         4019.0   52.0  
1       144.99340       Northern Metropolitan         4019.0  116.0  
2       144.99440       Northern Metropolitan         4019.0  117.0  
3       144.99690       Northern Metropolitan         4019.0   53.0  
4       144.99410       Northern Metropolitan         4019.0    2.0  
...           ...                         ...            ...    ...  
12908   144.89390       Northern Metropolitan         2474.0   53.0  
12909   145.16761  South-Eastern Metropolitan         7392.0   36.0  
12910   144.87904        Western Metropolitan         6380.0   22.0  
12911   144.88738        Western Metropolitan         6380.0   20.0  
12912   144.88449        Western Metropolitan         6543.0   97.0  

[12913 rows x 23 columns]

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [7]:
X= df[['Bedroom2','Bathroom','Landsize','BuildingArea','Propertycount','Car']]
y = df['Type']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, train_size = .80, random_state = 42)

# KNN

In [9]:
K = 4
model =  KNeighborsClassifier(n_neighbors = K)
model.fit(X_train,y_train)
y_predict = model.predict(X_test)

In [10]:
model.score(X_train,y_train) #akurasi

0.8792836398838335

In [11]:
model.score(X_test,y_test)

0.8385598141695703

In [12]:
print('KNN sebelum tuning')
print(classification_report(y_test, y_predict))

KNN sebelum tuning
              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1764
           1       0.79      0.73      0.76       599
           2       0.44      0.21      0.28       220

    accuracy                           0.84      2583
   macro avg       0.70      0.63      0.65      2583
weighted avg       0.82      0.84      0.82      2583



In [13]:
print(metrics.confusion_matrix(y_test, y_predict))

[[1680   54   30]
 [ 130  440   29]
 [ 108   66   46]]


# DecissionTree

In [14]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

In [15]:
tr = tree.DecisionTreeClassifier()

In [16]:
tr.fit(X_train,y_train)

DecisionTreeClassifier()

In [17]:
tr.score(X_train,y_train)

0.995837366892546

In [18]:
tr.score(X_test,y_test)

0.8068137824235385

In [19]:
y_dtc=tr.predict(X_test)
y_dtc

array([0, 1, 1, ..., 0, 0, 1], dtype=int64)

In [20]:
print('dt sebelum tuning')
print(classification_report(y_test, y_dtc))

dt sebelum tuning
              precision    recall  f1-score   support

           0       0.89      0.88      0.89      1764
           1       0.74      0.73      0.74       599
           2       0.35      0.38      0.37       220

    accuracy                           0.81      2583
   macro avg       0.66      0.67      0.66      2583
weighted avg       0.81      0.81      0.81      2583



# Logistic reg

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
modelLog = LogisticRegression()
modelLog.fit(X_train, y_train)

C:\Users\Hansen Marcelino\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
modelLog.score(X_test, y_test)

0.7077042198993418

In [24]:
modelLog.score(X_train,y_train)

0.707647628267183

In [25]:
LR=modelLog.predict(X_test)

In [26]:
print('dt sebelum tuning')
print(classification_report(y_test, LR))

dt sebelum tuning
              precision    recall  f1-score   support

           0       0.71      0.96      0.82      1764
           1       0.62      0.22      0.32       599
           2       0.00      0.00      0.00       220

    accuracy                           0.71      2583
   macro avg       0.45      0.39      0.38      2583
weighted avg       0.63      0.71      0.64      2583



C:\Users\Hansen Marcelino\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hansen Marcelino\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hansen Marcelino\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Hyperparameter tuning

In [27]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [28]:
tuning_DC = tree.DecisionTreeClassifier()
parameter_dc=  {'min_impurity_split': [None],
                'min_samples_leaf': [1],
                'min_samples_split': [2],
                'min_weight_fraction_leaf': [0.0,0.3,0.6,0.9]}

In [29]:
gridDT = GridSearchCV(estimator=tuning_DC, param_grid=parameter_dc, verbose=1, n_jobs=-1, cv=4)

In [30]:

gridDT.fit(X_train,y_train)

Fitting 4 folds for each of 4 candidates, totalling 16 fits


C:\Users\Hansen Marcelino\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [0.80135489 0.75769642        nan        nan]
  warnings.warn(


GridSearchCV(cv=4, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'min_impurity_split': [None], 'min_samples_leaf': [1],
                         'min_samples_split': [2],
                         'min_weight_fraction_leaf': [0.0, 0.3, 0.6, 0.9]},
             verbose=1)

In [31]:
# tuning_DC.get_params()

In [32]:

bestDC= gridDT.best_estimator_
bestDC

DecisionTreeClassifier()

In [33]:
DTC = bestDC.predict(X_test)

In [34]:
print(classification_report(y_test, DTC))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89      1764
           1       0.74      0.76      0.75       599
           2       0.36      0.35      0.36       220

    accuracy                           0.81      2583
   macro avg       0.66      0.67      0.67      2583
weighted avg       0.81      0.81      0.81      2583



In [35]:
gridDT.score(X_train,y_train)

0.995837366892546

In [36]:
gridDT.score(X_test,y_test)

0.8122338366240806

naik dikit

In [1]:
model yang paling baik adalah model KNN. karena mempunyai akurasi yang lbih tinggi dibandingkan yang lainnya.

SyntaxError: invalid syntax (<ipython-input-1-9ad30878db14>, line 1)